import assert from 'node:assert/strict';
import fs from 'node:fs';
const { state } = await import('../assets/js/core/state.js');
const { auditPage, auditFilters, resetAuditFilters, matchingAudit, valueText, auditTime, auditDay, operationLabel, auditGroup, auditActions, bindAuditPage } = await import('../assets/js/modules/audit/page.js');
state.user = { role: 'owner' };
state.currentPage = 'audit';
state.data = { settings: { company: 'Usaha <aman>' }, business_catalog: JSON.parse(fs.readFileSync(new URL('../app/business-catalog.json', import.meta.url))),
  products: [{ id: 'p1', name: 'Biji kopi', unit: 'kg' }], batches: [{ id: 'b1', product: 'p1' }], audit: [] };
const make = (i, extra = {}) => ({ id: 'log-' + i, time: '2026-10-03T18:00:00+07:00', user: 'Admin <script>', user_id: 'u1', role: 'admin', op: 'master.save', schema: 2, source: 'quick-edit', document: 'p1', summary: 'Harga berubah', changes: [{ entity: 'products', id: 'p1', label: '<img src=x onerror=1>', kind: 'updated', context: { unit: 'kg' }, fields: [{ key: 'price', before: 10000, after: 12000 }] }], ...extra });
state.data.audit = [make(0, { schema: undefined, user_id: undefined, changes: undefined, op: 'old.action' }), ...Array.from({ length: 30 }, (_, i) => make(i + 1))];
assert.equal(auditGroup('order.cancel'), 'sales');
assert.equal(auditGroup('opname.approve'), 'stock');
assert.equal(auditGroup('refund'), 'money');
assert.equal(auditDay('2026-10-03T18:30:00Z'), '2026-10-04');
assert.match(auditTime('2026-10-03T18:30:00Z'), /WIB/);
assert.equal(auditDay('broken'), '');
assert.equal(valueText(1500, 'qty', { batch: 'b1' }), '1,5 kg');
assert.equal(valueText(-500, 'qty', { product: 'p1' }), '-0,5 kg');
assert.equal(valueText(0, 'stock_balance', { unit: 'pcs' }), '0 pcs');
assert.equal(valueText(false), 'Tidak');
assert.match(valueText(12000, 'outstanding'), /Rp/);
assert.match(valueText([{ product: 'p1', qty: 1500 }]), /1,5 kg/);
let markup = auditPage();
assert.equal((markup.match(/<details class="audit-entry">/g) || []).length, 25);
assert.equal(state.exportRows.length, 31);
assert.ok(!markup.includes('<img src=x'));
assert.ok(markup.includes('&lt;img'));
assert.ok(!markup.includes('<script>'));
assert.match(markup, /Sebelum/);
assert.match(markup, /Sesudah/);
assert.match(markup, /Quick Edit/);
auditFilters.page = 2;
markup = auditPage();
assert.equal((markup.match(/<details class="audit-entry">/g) || []).length, 6);
assert.match(markup, /detail sebelum–sesudah belum direkam/);
state.searchQuery = 'simpan data master';
auditPage();
assert.equal(auditFilters.page, 1);
assert.equal(matchingAudit().length, 30);
resetAuditFilters();
auditFilters.user = 'legacy:Admin <script>';
assert.equal(matchingAudit().length, 1);
resetAuditFilters();
auditFilters.from = '2026-10-04';
assert.equal(matchingAudit().length, 0);
auditFilters.from = '2026-10-03'; auditFilters.until = '2026-10-03';
assert.equal(matchingAudit().length, 31);
auditFilters.group = 'money';
assert.equal(matchingAudit().length, 0);
resetAuditFilters();
auditFilters.record = 'p1';
assert.equal(matchingAudit().length, 31);
auditFilters.record = 'missing';
assert.equal(matchingAudit().length, 0);
assert.match(auditPage(), /Tidak ada aktivitas yang cocok/);
resetAuditFilters();
state.data.audit = [make(1, { op: 'pay', changes: [] })];
assert.match(auditPage(), /belum memiliki pembatalan langsung/);
state.data.audit = [make(1, { op: 'business.settings' })];
state.user.role = 'admin';
assert.ok(!auditPage().includes('href="#settings"'));
state.user.role = 'sales';
await assert.rejects(auditActions['audit-record']('', 'p1'), /owner dan admin/);
state.user.role = 'owner';
globalThis.location = { hash: '' };
await auditActions['audit-record']('', 'p1');
assert.equal(location.hash, 'audit');
assert.equal(auditFilters.record, 'p1');
const filter = { dataset: { auditFilter: 'group' }, value: 'stock' };
const next = { dataset: { auditPage: '2' } };
const reset = {};
let renders = 0;
globalThis.document = { querySelectorAll: (q) => q === '[data-audit-filter]' ? [filter] : [next], querySelector: () => reset };
bindAuditPage(() => renders++);
filter.onchange(); assert.equal(auditFilters.group, 'stock');
next.onclick(); assert.equal(auditFilters.page, 2);
reset.onclick(); assert.equal(auditFilters.record, ''); assert.equal(auditFilters.group, '');
assert.equal(renders, 3);
const commands = fs.readFileSync(new URL('../app/commands.php', import.meta.url), 'utf8').matchAll(/'([\w.]+)'\s*=>/g);
for (const [, op] of commands) assert.notEqual(operationLabel(op), op, 'Friendly label for ' + op);
console.log('PASS: audit legacy/new history, WIB boundary, filters, pagination, all-result export, HTML escaping, kg/pcs quantities, role gates, correction guidance and filter events. DOM/API simulated.');
