const { chromium: playwright } = await import(process.env.TERNUS_PLAYWRIGHT_PATH || 'playwright');
import { fileURLToPath } from 'node:url';
import os from 'node:os';
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const screenshots=fs.mkdtempSync(path.join(os.tmpdir(),'ternus-related-test-'));
const fixture=`<!doctype html><html lang="id"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/assets/css/app.css"><link rel="stylesheet" href="/assets/css/searchable-select.css"><div id="app"></div><dialog id="modal"></dialog><div id="toast"></div><script type="module">
import {receiveForm} from '/assets/js/modules/receiving/form.js';window.receiveForm=receiveForm;import {state} from '/assets/js/core/state.js';import {saleForm} from '/assets/js/modules/sales/form.js';import {initSearchableSelects} from '/assets/js/components/searchable-select.js';import {relatedCreate} from '/assets/js/components/related-create.js';import {commonActions} from '/assets/js/components/actions.js';
const data={customers:[{id:'c1',name:'Caterra Cafe',active:true}],locations:[{id:'l1',name:'Gudang',active:true}],suppliers:[],products:[{id:'p1',name:'Kopi Lama',sku:'KOPI',active:true,sell:true,unit:'kg',stage:'Green Beans',price:50000}],terms:[],settings:{business:{stages:['Green Beans']}}};state.data=structuredClone(data);state.user={id:'u1',name:'Owner',role:new URLSearchParams(location.search).get('role')||'owner'};state.currentPage='quotes';state.csrfToken='test';window.saved=[];const requests=new Map();window.failRefresh=false;window.failSave=false;
window.fetch=async(url,options)=>{let result;
if(url.endsWith('mutate')){const req=JSON.parse(options.body);if(window.failSave){return{ok:false,json:async()=>({error:'Nama atau SKU ditolak'})};}if(requests.has(req.key))result=requests.get(req.key);else{const record={...req.data,id:'new-'+(window.saved.length+1),active:true};window.saved.push(record);data[record.type].push(record);result={result:{id:record.id,message:'Data tersimpan.'}};requests.set(req.key,result);}}
else {if(window.failRefresh){window.failRefresh=false;return{ok:false,json:async()=>({error:'Koneksi terputus, coba lagi'})};}result={state:structuredClone(data),user:state.user,csrf:'test'};}return{ok:true,json:async()=>result};};
document.addEventListener('click',async event=>{const b=event.target.closest('[data-act]');if(b&&commonActions[b.dataset.act]){event.preventDefault();await commonActions[b.dataset.act](b.dataset.act,b.dataset.id,b);}});
initSearchableSelects({relatedCreate});saleForm(true);window.ready=true;window.state=state;
</script>`;
const server=http.createServer((req,res)=>{const url=req.url.split('?')[0];if(url==='/'){res.setHeader('Content-Type','text/html');return res.end(fixture);}try{res.setHeader('Content-Type',url.endsWith('.js')?'text/javascript':url.endsWith('.css')?'text/css':'text/plain');res.end(fs.readFileSync(path.join(root,url)));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{
browser=await playwright.launch({executablePath:process.env.TERNUS_CHROMIUM_PATH || undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu'],headless:true});const page=await browser.newPage({viewport:{width:1100,height:900}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const url='http://127.0.0.1:'+server.address().port;await page.goto(url);await page.waitForFunction(()=>window.ready);
await page.locator('#modal [name=shipping]').fill('37500');await page.locator('#modal [data-field=qty]').fill('2');await page.locator('#modal [data-field=price]').fill('123456');await page.locator('#modal [data-field=discount]').fill('500');
await page.evaluate(()=>window.parentForm=document.querySelector('#modal form'));
await page.getByRole('button',{name:'+ Tambah pelanggan',exact:true}).click();
const child=page.locator('#related-create-modal');await child.locator('[name=name]').fill('Pelanggan Baru');await child.locator('[name=phone]').fill('081234567890');await child.locator('[name=address]').fill('Bandung');
assert.equal(await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(x=>x.id);return ids.length===new Set(ids).size;}),true);
await page.screenshot({path:path.join(screenshots,'desktop.png')});
await child.getByRole('button',{name:'Simpan',exact:true}).click();await child.waitFor({state:'detached'});
assert.equal(await page.locator('#modal [name=customer]').inputValue(),'new-1');assert.equal(await page.locator('#modal [name=shipping]').inputValue(),'37500');assert.equal(await page.locator('[data-field=qty]').inputValue(),'2');assert.equal(await page.locator('[data-field=price]').inputValue(),'123456');assert.equal(await page.locator('[data-field=discount]').inputValue(),'500');assert.equal(await page.evaluate(()=>document.querySelector('#modal form')===window.parentForm),true);
await page.getByRole('button',{name:'+ Tambah lokasi',exact:true}).click();await child.locator('[name=name]').fill('Batal');await child.getByRole('button',{name:'Kembali',exact:true}).click();await child.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>window.saved.length),1);assert.equal(await page.locator('#modal').evaluate(e=>e.open),true);
await page.getByRole('button',{name:'+ Tambah barang',exact:true}).click();await child.locator('[name=name]').fill('Produk Baru');assert.equal(await child.locator('[name=sku]').inputValue(),'PRODUK-BARU');await child.locator('[name=price]').fill('25000');await page.evaluate(()=>window.failSave=true);await child.getByRole('button',{name:'Simpan',exact:true}).click();await child.locator('.error').waitFor();assert.equal(await child.locator('[name=name]').inputValue(),'Produk Baru');
await page.evaluate(()=>{window.failSave=false;window.failRefresh=true;});await child.getByRole('button',{name:'Simpan',exact:true}).click();await page.getByText('Koneksi terputus, coba lagi',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.saved.length),2);
await child.getByRole('button',{name:'Simpan',exact:true}).click();await child.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>window.saved.length),2);assert.equal(await page.locator('#lines select').inputValue(),'new-2');assert.equal(await page.locator('[data-field=price]').inputValue(),'25000');assert.equal(await page.locator('[data-field=qty]').inputValue(),'2');
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'+ Tambah pelanggan',exact:true}).click();await child.locator('[name=name]').fill('Pelanggan Mobile');await page.screenshot({path:path.join(screenshots,'mobile.png')});await page.keyboard.press('Escape');await child.waitFor({state:'detached'});assert.equal(await page.locator('#modal').evaluate(e=>e.open),true);
await page.setViewportSize({width:1100,height:900});await page.evaluate(()=>window.receiveForm());
for(const [label,field] of [['vendor','supplier'],['lokasi','location']]){
await page.getByRole('button',{name:'+ Tambah '+label,exact:true}).click();await child.locator('[name=name]').fill('Baru '+label);await child.getByRole('button',{name:'Simpan',exact:true}).click();await child.waitFor({state:'detached'});assert.match(await page.locator('#modal [name='+field+']').inputValue(),/^new-/);assert.equal(await page.locator('#modal').evaluate(e=>e.open),true);
}
await page.goto(url+'/?role=sales');await page.waitForFunction(()=>window.ready);assert.equal(await page.getByRole('button',{name:'+ Tambah pelanggan',exact:true}).count(),1);assert.equal(await page.getByRole('button',{name:'+ Tambah barang',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'+ Tambah lokasi',exact:true}).count(),0);assert.deepEqual(errors,[]);
console.log('PASS: actual quotation form preserves parent node and drafts; creates/selects customer/product/vendor/location; product SKU/price; cancel/Escape; validation failure; refresh retry without duplicate; role gates; desktop/mobile. API simulated.');
}finally{await browser?.close();server.close();}
