import assert from 'node:assert/strict';
// Developer-only: install jsdom@26.1.0 in an isolated test environment.
const { JSDOM } = await import(process.env.TERNUS_JSDOM_PATH || 'jsdom');
const dom = new JSDOM('<body><div id="app"></div><dialog id="modal" open><form id="form"><label for="item">Barang</label><select id="item" name="product" required><option value="">Pilih…</option><option value="a">Arabica Honey · ARB-HNY</option><option value="b">Robusta Natural</option><option disabled value="c">Disabled</option></select><button type="submit">Simpan</button></form></dialog></body>', { url: 'http://localhost/', pretendToBeVisual: true });
for (const key of ['window','document','Element','MutationObserver','Event','KeyboardEvent','CustomEvent','FormData']) globalThis[key] = dom.window[key];
const { initSearchableSelects } = await import('../assets/js/components/searchable-select.js');
initSearchableSelects(); initSearchableSelects();
const tick = () => new Promise(r => setTimeout(r, 20));
const select = document.querySelector('#item'), input = select.parentNode.querySelector('.search-select-input');
assert.equal(document.querySelectorAll('.search-select').length, 1);
let changes = 0; select.onchange = () => changes++;
const type = (text) => { input.value = text; input.dispatchEvent(new Event('input', {bubbles:true})); };
const key = (name) => input.dispatchEvent(new KeyboardEvent('keydown', {key:name,bubbles:true,cancelable:true}));
input.focus(); assert.equal(input.getAttribute('aria-expanded'), 'true');
assert.equal(document.querySelector('.search-select-list').parentNode.id, 'modal');
type('hny'); assert.equal(document.querySelectorAll('[role=option]').length,1);
key('Enter'); assert.equal(select.value,'a'); assert.equal(changes,1);
assert.equal(new FormData(document.querySelector('#form')).get('product'),'a');
assert.equal(input.value,'Arabica Honey · ARB-HNY');
input.click(); type('not found'); assert.match(document.querySelector('.search-select-list').textContent,/Tidak ada hasil/);
key('Enter'); assert.equal(select.value,'a'); key('Escape'); assert.equal(input.value,'Arabica Honey · ARB-HNY');
input.click(); type('robusta'); key('Tab'); assert.equal(select.value,'a');
input.click(); type('ROBUSTA'); document.querySelector('[role=option]').click(); assert.equal(select.value,'b'); assert.equal(changes,2);
select.value=''; select.dispatchEvent(new Event('change')); assert.equal(input.value,'');
select.reportValidity(); assert.equal(document.activeElement,input); assert.equal(input.getAttribute('aria-invalid'),'true');
key('Escape'); select.disabled=true; await tick(); assert.equal(input.disabled,true);
select.disabled=false; select.required=false; await tick(); assert.equal(input.disabled,false); assert.equal(input.getAttribute('aria-required'),'false');
select.insertAdjacentHTML('beforeend','<option value="d">Café &lt;img src=x&gt;</option>'); await tick();
input.focus(); type('cafe'); assert.equal(document.querySelectorAll('[role=option]').length,1); assert.equal(document.querySelectorAll('.search-select-list img').length,0);
key('Enter'); assert.equal(select.value,'d');
document.querySelector('#form').reset(); await tick(); assert.equal(input.value,'');
const form=document.querySelector('#form'); form.insertAdjacentHTML('beforeend','<select data-field="batch"><option value="one">Batch One</option><option value="two">Batch Two</option></select>'); await tick();
assert.equal(document.querySelectorAll('.search-select').length,2);
const batch=form.querySelector('[data-field=batch]');batch.parentNode.querySelector('input').focus();
batch.parentNode.remove(); await tick(); assert.equal(document.querySelector('.search-select-list'),null);
input.focus(); document.querySelector('#modal').removeAttribute('open'); await tick();assert.equal(document.querySelector('.search-select-list'),null);
console.log('PASS: search, SKU, keyboard, click, no-results, preserved ID/FormData, change events, required, disabled, reset, dynamic rows, safe labels and cleanup.');
dom.window.close();
