import assert from 'node:assert/strict';
const form = { querySelector: () => error }, error = { innerHTML: '' }, feedback = { style: {} };
const modal = { querySelector: () => form, innerHTML: '', showModal() {}, close() { this.closed = true; } };
globalThis.document = { querySelector: s => ({ '#modal': modal, '#modal-form': form, '#form-error': error, '#toast': feedback })[s] || {} };
globalThis.window = new EventTarget();
globalThis.CustomEvent ??= class extends Event { constructor(name) { super(name); } };
globalThis.FormData = class { constructor() {} *[Symbol.iterator]() { yield ['confirmed', 'on']; } };
const { state } = await import('../assets/js/core/state.js');
const { storagePanel, storageActions } = await import('../assets/js/modules/settings/storage.js');
state.user = { role: 'owner' }; state.data = { settings: {} }; state.csrfToken = 'test-csrf';
state.storage = null; assert.equal(storagePanel(), '');
state.storage = { mode: 'legacy' };
assert.match(storagePanel(), /Migrasi Database/); assert.match(storagePanel(), /Unduh Backup/);
await storageActions['database-migrate']();
assert.match(modal.innerHTML, /type="checkbox" name="confirmed" required/);
const calls = [];
globalThis.fetch = async (url, options) => {
  calls.push([url, options]);
  return { ok: true, json: async () => url.endsWith('migrate') ? { message: 'Migrasi berhasil' } : { state: { settings: {} }, user: state.user, csrf: 'new-csrf', storage: { mode: 'relational', table_count: 40, migrated_at: '<script>' } } };
};
const button = { disabled: false };
await form.onsubmit({ preventDefault() {}, target: { querySelector: () => button } });
assert.equal(calls[0][0], 'api.php?action=migrate');
assert.equal(calls[0][1].method, 'POST');
assert.deepEqual(JSON.parse(calls[0][1].body), { confirm: true });
assert.equal(calls[0][1].headers['X-CSRF-Token'], 'test-csrf');
assert.equal(calls[1][0], 'api.php?action=state');
assert.equal(state.storage.mode, 'relational'); assert.equal(modal.closed, true);
assert.equal(button.disabled, false); assert.equal(state.busy, false);
assert.match(storagePanel(), /40 tabel data/); assert.match(storagePanel(), /&lt;script&gt;/);
assert.doesNotMatch(storagePanel(), /data-action="database-migrate"/);
console.log('PASS: migration panel, backup confirmation, POST/CSRF, reload and active status (DOM/API simulated).');
